### ISSUE TITLE
No themes directory

### ISSUE THREAD

**Issue by texjunky** [gevhaz/hugo-theme-notrack#23]
I am new to hugo. I followed the instructions for running the exampleSite in notrack. I loved the site and now want to convert it to a regular site and substitute my own content. I am puzzled that I cannot find a themes directory anywhere.

**Comment by gevhaz** [comment]
Hi, thanks for trying out the theme!

Could you describe in more detail what your issue is? In general, the process for creating a new site using this theme would be as described in the [Create a site](https://gohugo.io/getting-started/quick-start/#create-a-site) section of the Hugo web page. The difference is just that you need to change this command:

```
echo "theme = 'ananke'" >> config.toml
```

to say "notrack" instead of "ananke". You can also take a look at my [example site config](https://github.com/gevhaz/hugo-theme-notrack#example-site-config) instead. The "site config" is the `config.toml` in the command.

Once you have a new Hugo project as described in the link, you can `cd` to the `themes` directory and clone my theme to there:

```
cd themes/
git clone https://github.com/gevhaz/hugo-theme-notrack/
```

Please close the issue if this solves your problem, or let me know if it doesn't :)

**Comment by texjunky** [comment]
Thanks much. I have it working.
Your example site demonstrates so much creativity on your part.
